### ISSUE TITLE
ChordProParser: Nesting curly brace

### ISSUE THREAD

**Issue by Glidias** [martijnversluis/ChordSheetJS#253]
Nesting brackets in curly brace:
`{comment: Intro [Dm7] [F6/B] [Cmaj7]  }`

https://www.chordpro.org/chordpro/chordpro-chords/

```
peg$SyntaxError: Expected "}" or [a-zA-Z0-9 ] but "[" found.
    at peg$buildStructuredError (C:\Glenn\_dev\Git\gingkstep\node_modules\chordsheetjs\lib\parser\chord_pro_peg_parser.js:454:12)
    at Object.peg$parse [as parse] (C:\Glenn\_dev\Git\gingkstep\node_modules\chordsheetjs\lib\parser\chord_pro_peg_parser.js:1780:11)
    ```

**Comment by martijnversluis** [comment]
Hey @Glidias ! Thanks for reporting this issue 👍 

I just published version [4.1.0](https://github.com/martijnversluis/ChordSheetJS/releases/tag/v4.1.0) which fixes this bug.
